name: Linting
on:
  push:
    branches:
      - main
      - master
      - '*'
  pull_request:
    branches:
      - main
      - master
jobs:
  my-First-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Say hello
        run: echo 'Hello world!'
