name: Linting
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  my-First-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'
      - name: Install dependencies
        run: npm ci --audit=false --fund=false
        env:
          CI: false
      - name: check linting
        run: npm run lint --skip-nx-cache
