name: Publish library
on:
  workflow_dispatch:
    inputs:
      library:
        description: 'Labrary'
        required: true
        type: choice
        options:
          - components
          - hooks
      publish:
        description: 'Publish package to registry'
        required: false
        type: boolean
      increment:
        description: 'Increment the version of package'
        required: false
        type: boolean
      incrementType:
        description: 'Incremention Type'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Publish the library
        if: ${{inputs.publish}}
        run: echo ${{inputs.library}}
