name: Publish library
on:
  workflow_dispatch:
    inputs:
      library:
        description: 'Library'
        required: true
        type: choice
        options:
          - components
          - hooks

jobs:
  publish_library:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo 'Hello world!'
      - name: say good bye
        run: echo 'Good bye!'
