name: Publish library
on:
  workflow_dispatch:
    inputs:
      library:
        description: 'Library'
        required: true
        type: choice
        options:
          - components
          - hooks
