name: Publish library
on:
  workflow_dispatch:
    inputs:
      library:
        description: 'Labrary'
        required: true
        type: choice
        options:
          - components
          - hooks
    publish:
      description: 'Publish package to registry'
      required: false
      type: boolean

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Publish the library
         run: echo 'published ${{ inputs.library}}' 
